name: PolyNome
favicon: null
layout_spectrum: 0.19663064344786108
typography_spectrum: 0.2575667679775506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fedafd'
    - '#1a3162'
    - '#6c9ec8'
    - '#734d97'
    - '#fed130'
  brandStrength: 0.5
  lightness: 0.7704435863997787
  saturation: 0.6991872186772525
  rhythmicContrast: 0.2843561281915754
purpose: []
